export const activityDemo = {
  executions: [
    {
      _id: "exec-001",
      summary: "Optimism rebalance approved",
      kind: "swap",
      status: "filled",
      detail: "The worker detected LINK inventory drift and asked Convex to sign a bounded Uniswap-side rebalance.",
      txHash: "0x6fe712b31f7c91d784fc40e0c523d6128cb9d86a4f0c11f1aa91db22a0771bb1",
    },
    {
      _id: "exec-002",
      summary: "HyperLiquid hedge refreshed",
      kind: "hedge",
      status: "filled",
      detail: "Short exposure was nudged back toward the configured target after the latest LP-side move settled.",
      txHash: "0x5f3ef1ab912c8dc30a11930b59f1a147d5f7882c6f8a2c119afe80f85b955e08",
    },
    {
      _id: "exec-003",
      summary: "Withdrawal request staged",
      kind: "withdrawal",
      status: "skipped",
      detail: "A queued withdrawal was left pending until fresh wallet balances were confirmed by the manual refresh path.",
      requestId: "wd-demo-queued-002",
    },
    {
      _id: "exec-004",
      summary: "Gas reserve top-up flagged",
      kind: "alert",
      status: "failed",
      detail: "The worker refused to force a chain-side action while the ETH reserve was still below the preferred threshold.",
      requestId: "incident-gas-watch-001",
    },
    {
      _id: "exec-005",
      summary: "Activity projection refreshed",
      kind: "snapshot",
      status: "filled",
      detail: "A fresh snapshot and wallet inventory read were written back into the strategy account after both venues synced.",
      requestId: "snapshot-1777881783",
    },
    {
      _id: "exec-006",
      summary: "Second HyperLiquid readiness check",
      kind: "sync",
      status: "filled",
      detail: "A follow-up readiness pass confirmed the agent wallet approval was still active and the hedge rail stayed runnable.",
      requestId: "sync-1777881761",
    },
  ],
  auditEvents: [
    {
      _id: "audit-001",
      summary: "Execution mode changed to live",
      kind: "config_updated",
      actor: "operator",
      detail: "The demo account moved out of paper mode once all three wallets were provisioned and approved.",
    },
    {
      _id: "audit-002",
      summary: "HyperLiquid agent approved",
      kind: "approval",
      actor: "system",
      detail: "Master wallet approval succeeded and the delegated trading wallet became usable for hedge placement.",
    },
    {
      _id: "audit-003",
      summary: "Withdrawal cancelled",
      kind: "withdrawal_cancelled",
      actor: "viewer",
      detail: "{\"destination\":\"0x21ab9c2838fedbf1b7a601f526816f28871c2\",\"reason\":\"inventory buffer protected\"}",
    },
    {
      _id: "audit-004",
      summary: "Margin top-up acknowledged",
      kind: "deposit_confirmed",
      actor: "system",
      detail: "Margin capital was confirmed after the latest HyperLiquid funding transfer landed.",
    },
    {
      _id: "audit-005",
      summary: "Risk review recorded",
      kind: "operator_note",
      actor: "operator",
      detail: "Operator accepted the current gas-reserve warning and scheduled a funding top-up for the next manual check.",
    },
    {
      _id: "audit-006",
      summary: "Snapshot replay exported",
      kind: "audit_exported",
      actor: "viewer",
      detail: "Synthetic marketing fixture export created for product walkthrough capture.",
    },
  ],
  incidents: [
    {
      _id: "inc-001",
      code: "gas_reserve_low",
      summary: "Optimism gas reserve needs replenishment before a heavier onchain cycle begins.",
      severity: "warning",
      detail: "This incident stays visible until ETH reserve recovers above the preferred runway threshold.",
    },
    {
      _id: "inc-002",
      code: "inventory_drift_watch",
      summary: "Inventory drift widened after the last LP rebalance, but recovered before a hard pause was required.",
      severity: "info",
      detail: "Synthetic marketing fixture incident to make the activity stream visually legible.",
    },
  ],
  withdrawals: [
    { _id: "wd-001", amount: "0.0006312", asset: "ETH", status: "completed", destination: "0x21ab9c2838fedbf1b7a601f526816f28871c2" },
    { _id: "wd-002", amount: "125.00", asset: "USDC", status: "queued", destination: "0x31b2c8838fddb1dff5601f536916f23871c3" },
    { _id: "wd-003", amount: "0.0006311", asset: "ETH", status: "cancelled", destination: "0x41ab9c2838fedbf1b7a601f526816f28871c4" },
    { _id: "wd-004", amount: "240.00", asset: "USDC", status: "pending_checks", destination: "0x51ab9c2838fedbf1b7a601f526816f28871c5" },
    { _id: "wd-005", amount: "0.0006200", asset: "ETH", status: "completed", destination: "0x61ab9c2838fedbf1b7a601f526816f28871c6" },
    { _id: "wd-006", amount: "80.00", asset: "USDC", status: "failed", destination: "0x71ab9c2838fedbf1b7a601f526816f28871c7" },
  ],
} as const;
