export const depositsDemo = [
  {
    venueAccountId: "optimism_execution_wallet",
    role: "optimism execution wallet",
    venue: "Optimism / Uniswap",
    chainRef: "eip155:10",
    walletAddress: "0x1bca20a91e5b9fd0344de1be59f5c12daf8fc2",
    status: "ready",
    lastSyncedAt: 1777881783000,
    lastSyncStatus: "fresh",
    lastSyncError: null,
    totalWalletHoldingsUsd: 9182.44,
    strategyAssetValueUsd: 9067.61,
    gasReserveValueUsd: 114.83,
    lowGasWarning: {
      asset: "ETH",
      currentBalance: "0.0301",
      message: "Synthetic demo fixture: top up ETH if the Optimism wallet starts processing more chain actions.",
    },
    note: "Fund USDC for LP-side strategy actions, LINK for inventory balance, and ETH for operational gas.",
    strategyAssets: [
      {
        asset: "USDC",
        label: "Strategy capital",
        balance: "6,024.92",
        valueUsd: 6024.92,
        availableBalance: "5,820.00",
        withdrawNote: "A small buffer stays allocated to in-flight onchain work.",
      },
      {
        asset: "LINK",
        label: "Inventory buffer",
        balance: "53.62",
        valueUsd: 3042.69,
        availableBalance: "53.62",
        withdrawNote: "Inventory can remain parked here even when no rebalance is active.",
      },
    ],
    operationalAssets: [
      {
        asset: "ETH",
        label: "Gas reserve",
        balance: "0.0301",
        valueUsd: 114.83,
        availableBalance: "0.0184",
        withdrawNote: "Operational gas reserve is intentionally only partly withdrawable.",
      },
    ],
    recentTransfers: [
      {
        id: "dep-tx-001",
        asset: "USDC",
        purpose: "strategy",
        direction: "in",
        amount: "3,500.00",
        balanceAfter: "6,024.92",
        valueUsd: 3500,
        observedAt: 1777881329000,
        detail: "Funding landed from the managed deposit rail and was written into wallet inventory.",
      },
      {
        id: "dep-tx-002",
        asset: "ETH",
        purpose: "gas",
        direction: "in",
        amount: "0.0100",
        balanceAfter: "0.0301",
        valueUsd: 38.17,
        observedAt: 1777881209000,
        detail: "Operational gas top-up landed before the latest worker reconciliation.",
      },
    ],
    depositRecords: [
      { id: "dep-rec-001", asset: "USDC", status: "confirmed" },
      { id: "dep-rec-002", asset: "LINK", status: "detected" },
      { id: "dep-rec-003", asset: "ETH", status: "confirmed" },
    ],
  },
  {
    venueAccountId: "hyperliquid_master_wallet",
    role: "hyperliquid master wallet",
    venue: "HyperLiquid",
    chainRef: "hyperliquid",
    walletAddress: "0x6f15f4216f10dc884215a5912d607de3d1659de3658a59521707f",
    status: "ready",
    lastSyncedAt: 1777881761000,
    lastSyncStatus: "fresh",
    lastSyncError: null,
    totalWalletHoldingsUsd: 9230.12,
    strategyAssetValueUsd: 9230.12,
    gasReserveValueUsd: 0,
    lowGasWarning: null,
    note: "Fund the HyperLiquid master wallet for margin and withdrawals. Agent execution stays delegated separately.",
    strategyAssets: [
      {
        asset: "USDC",
        label: "Margin capital",
        balance: "9,230.12",
        valueUsd: 9230.12,
        availableBalance: "8,900.00",
        withdrawNote: "Keep a margin buffer if the hedge side is expected to reopen quickly.",
      },
    ],
    operationalAssets: [],
    recentTransfers: [
      {
        id: "dep-tx-003",
        asset: "USDC",
        purpose: "strategy",
        direction: "in",
        amount: "4,000.00",
        balanceAfter: "9,230.12",
        valueUsd: 4000,
        observedAt: 1777881109000,
        detail: "Margin funding landed before the hedge account was marked ready.",
      },
    ],
    depositRecords: [{ id: "dep-rec-004", asset: "USDC", status: "confirmed" }],
  },
] as const;
